//! Declarative project delivery rules. Disabled stages never enable one another.
use crate::board::Task;
use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};

pub fn saved(data: &std::path::Path, id: &str) -> Policy {
    crate::repo::saved_project_settings(data, id)
        .delivery
        .unwrap_or_else(|| {
            let dispatch: crate::dispatch::DispatchState = crate::db::load_state(data, "dispatch");
            Policy {
                auto_merge: dispatch.merge_when_checks_pass,
                ..Default::default()
            }
        })
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(default)]
pub struct Policy {
    pub auto_commit: bool,
    pub auto_push: bool,
    pub auto_pr: bool,
    pub auto_merge: bool,
    /// `finished` observes an explicit finished report; `review` observes the
    /// review column; `manual` runs only when the workflow tool/button is used.
    pub trigger: String,
    pub commit_template: String,
    pub default_type: String,
    pub rules: Vec<TypeRule>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TypeRule {
    #[serde(default)]
    pub issue_label: String,
    #[serde(default)]
    pub title_prefix: String,
    pub commit_type: String,
}

impl Default for Policy {
    fn default() -> Self {
        Self {
            auto_commit: false,
            auto_push: false,
            auto_pr: false,
            auto_merge: false,
            trigger: "finished".into(),
            commit_template: "{type}: {summary} [{task_id}]".into(),
            default_type: "chore".into(),
            rules: vec![
                TypeRule {
                    issue_label: "bug".into(),
                    title_prefix: "fix:".into(),
                    commit_type: "fix".into(),
                },
                TypeRule {
                    issue_label: "enhancement".into(),
                    title_prefix: "feat:".into(),
                    commit_type: "feat".into(),
                },
                TypeRule {
                    issue_label: "documentation".into(),
                    title_prefix: "docs:".into(),
                    commit_type: "docs".into(),
                },
            ],
        }
    }
}

fn valid_type(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 24
        && value.chars().all(|c| c.is_ascii_lowercase() || c == '-')
}

pub fn validate_message(message: &str) -> Result<()> {
    if message.trim().is_empty() || message.len() > 16_000 {
        bail!("commit message is empty or too long");
    }
    if message
        .chars()
        .any(|c| c.is_control() && c != '\n' && c != '\t')
    {
        bail!("commit message contains control characters");
    }
    for line in message.lines() {
        let line = line
            .trim()
            .trim_start_matches(|c: char| !c.is_alphanumeric())
            .to_lowercase();
        let attribution = line.starts_with("co-authored-by:")
            || line.starts_with("generated with")
            || line.starts_with("generated by")
            || line.starts_with("written by")
            || line.starts_with("assisted by")
            || line.starts_with("ai-generated")
            || line.starts_with("this commit was generated");
        let names_ai = [
            "claude",
            "codex",
            "gemini",
            "openai",
            "anthropic",
            "copilot",
            "chatgpt",
            "cursor",
            "aider",
            "assistant",
            "ai-generated",
        ]
        .iter()
        .any(|name| line.contains(name))
            || line
                .split(|c: char| !c.is_alphanumeric())
                .any(|word| word == "ai" || word == "gpt");
        if attribution && names_ai {
            bail!("remove AI attribution from the commit message; describe the change and its task/issue instead");
        }
    }
    Ok(())
}

impl Policy {
    pub fn validate(&self) -> Result<()> {
        if !matches!(self.trigger.as_str(), "finished" | "review" | "manual") {
            bail!("unknown delivery trigger");
        }
        if !valid_type(&self.default_type) || self.rules.len() > 32 {
            bail!("invalid commit classification settings");
        }
        for rule in &self.rules {
            if !valid_type(&rule.commit_type)
                || (rule.issue_label.is_empty() && rule.title_prefix.is_empty())
                || rule.issue_label.len() > 100
                || rule.title_prefix.len() > 100
            {
                bail!("a classification rule needs a label or title prefix and a lowercase commit type");
            }
        }
        if self.commit_template.len() > 500 || self.commit_template.contains(['\n', '\r']) {
            bail!("commit template must be one short line");
        }
        let mut remaining = self.commit_template.clone();
        for key in [
            "type",
            "summary",
            "task_id",
            "issue",
            "issue_number",
            "project",
        ] {
            remaining = remaining.replace(&format!("{{{key}}}"), "value");
        }
        if remaining.contains(['{', '}']) || !self.commit_template.contains("{summary}") {
            bail!("template requires {{summary}}; supported fields: type, summary, task_id, issue, issue_number, project");
        }
        validate_message(&remaining)
    }

    pub fn message(&self, task: &Task) -> Result<String> {
        self.validate()?;
        let title = task.title.trim();
        let conventional = title.split_once(':').and_then(|(prefix, summary)| {
            let kind = prefix
                .split('(')
                .next()
                .unwrap_or(prefix)
                .trim_end_matches('!')
                .to_ascii_lowercase();
            [
                "feat", "fix", "docs", "refactor", "test", "perf", "build", "ci", "chore", "style",
                "revert",
            ]
            .contains(&kind.as_str())
            .then_some((kind, summary.trim()))
        });
        let kind = self
            .rules
            .iter()
            .find(|rule| {
                (!rule.title_prefix.is_empty()
                    && title
                        .to_lowercase()
                        .starts_with(&rule.title_prefix.to_lowercase())
                    || conventional.as_ref().is_some_and(|(kind, _)| {
                        rule.title_prefix.eq_ignore_ascii_case(&format!("{kind}:"))
                    }))
                    || (!rule.issue_label.is_empty()
                        && task.issue.as_ref().is_some_and(|issue| {
                            issue
                                .labels
                                .iter()
                                .any(|label| label.eq_ignore_ascii_case(&rule.issue_label))
                        }))
            })
            .map(|rule| rule.commit_type.as_str())
            .unwrap_or_else(|| {
                conventional
                    .as_ref()
                    .map(|(kind, _)| kind.as_str())
                    .unwrap_or(&self.default_type)
            });
        let summary = conventional
            .as_ref()
            .map(|(_, summary)| *summary)
            .unwrap_or(title)
            .trim();
        let summary: String = summary
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ")
            .chars()
            .take(90)
            .collect();
        if summary.is_empty() {
            bail!("task needs a descriptive title before committing");
        }
        let issue = task
            .issue
            .as_ref()
            .map(|issue| issue.number.to_string())
            .unwrap_or_default();
        // Replace placeholders in a single pass so task text is never interpreted as a template.
        let fields = [
            ("type", kind),
            ("summary", summary.as_str()),
            ("task_id", &task.id),
            ("issue_number", &issue),
            ("project", &task.repository_id),
        ];
        let issue_ref = if issue.is_empty() {
            String::new()
        } else {
            format!("#{issue}")
        };
        let mut message = String::new();
        let mut rest = self.commit_template.as_str();
        while let Some((literal, tail)) = rest.split_once('{') {
            message.push_str(literal);
            let (key, tail) = tail.split_once('}').expect("validated template");
            message.push_str(if key == "issue" {
                &issue_ref
            } else {
                fields
                    .iter()
                    .find(|(name, _)| *name == key)
                    .expect("validated field")
                    .1
            });
            rest = tail;
        }
        message.push_str(rest);
        let message = message.trim().to_owned();
        if message.chars().count() > 200 {
            bail!("rendered commit subject exceeds 200 characters; shorten the template or title");
        }
        validate_message(&message)?;
        Ok(message)
    }

    pub fn permits_agent(&self, stage: &str, task: &Task) -> bool {
        self.trigger != "manual"
            && (self.trigger != "review"
                || matches!(
                    task.column,
                    crate::board::Column::Review | crate::board::Column::Ready
                ))
            && match stage {
                "commit" => self.auto_commit,
                "push" => self.auto_push,
                "pr" => self.auto_pr,
                "merge" => self.auto_merge,
                _ => false,
            }
    }

    pub fn instructions(&self) -> String {
        format!("\n\n## Delivery workflow\nUse workflow_run with the task_id when implementation is finished. Only enabled stages may run without a person's explicit action. Do not bypass disabled stages using git, gh, shell commands, other tools, or a downstream PR action. Never add AI attribution, Generated-with footers, or AI co-author trailers to commits. Describe the work; mentioning a product as the subject of a real change is fine. Disabled stages wait for the person. Existing commits/remote branches/PRs can satisfy prerequisites without enabling their creation. Merge always requires independent checks on the exact current commit. Policy:\n{}\n", serde_json::to_string_pretty(self).unwrap_or_default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn task() -> Task {
        serde_json::from_value(serde_json::json!({"id":"task42","title":"Repair startup","column":"review","repository_id":"demo","issue":{"number":17,"url":"https://example.com/17","labels":["bug"]}})).unwrap()
    }

    #[test]
    fn legacy_settings_keep_delivery_opt_in() {
        let settings: crate::project_settings::ProjectSettings =
            serde_json::from_str("{}").unwrap();
        assert!(settings.delivery.is_none());
        let policy: Policy = serde_json::from_str("{}").unwrap();
        assert!(!policy.auto_commit && !policy.auto_push && !policy.auto_pr && !policy.auto_merge);
        let issue: crate::board::Issue = serde_json::from_str(r#"{"number":1,"url":"x"}"#).unwrap();
        assert!(issue.labels.is_empty());
    }

    #[test]
    fn issue_classification_and_templates_are_literal() {
        let mut policy = Policy::default();
        assert_eq!(
            policy.message(&task()).unwrap(),
            "fix: Repair startup [task42]"
        );
        policy.commit_template = "{type}({project}): {summary} ({issue}; {task_id})".into();
        let mut task = task();
        task.title = "Handle {issue} literally".into();
        assert_eq!(
            policy.message(&task).unwrap(),
            "fix(demo): Handle {issue} literally (#17; task42)"
        );
        task.issue = None;
        task.title = "refactor(core): simplify startup".into();
        assert_eq!(
            Policy::default().message(&task).unwrap(),
            "refactor: simplify startup [task42]"
        );
        task.title = "feat: Add project settings".into();
        assert_eq!(
            Policy::default().message(&task).unwrap(),
            "feat: Add project settings [task42]"
        );
    }

    #[test]
    fn attribution_is_rejected_without_banning_product_names() {
        for text in [
            "fix: startup\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
            "Generated with Codex",
            "🤖 Generated by Gemini",
            "AI-generated change",
        ] {
            assert!(validate_message(text).is_err(), "{text}");
        }
        for text in [
            "fix: detect Codex usage limits",
            "feat: support Claude and Gemini",
            "fix: startup\n\nCo-authored-by: Ege <ege@example.com>",
        ] {
            assert!(validate_message(text).is_ok(), "{text}");
        }
    }

    #[test]
    fn stage_switches_are_independent_and_triggers_apply() {
        for bits in 0..16 {
            let mut policy = Policy {
                auto_commit: bits & 1 != 0,
                auto_push: bits & 2 != 0,
                auto_pr: bits & 4 != 0,
                auto_merge: bits & 8 != 0,
                ..Default::default()
            };
            for (index, stage) in ["commit", "push", "pr", "merge"].iter().enumerate() {
                assert_eq!(
                    policy.permits_agent(stage, &task()),
                    bits & (1 << index) != 0
                );
            }
            policy.trigger = "manual".into();
            for stage in ["commit", "push", "pr", "merge"] {
                assert!(!policy.permits_agent(stage, &task()));
            }
            policy.trigger = "review".into();
            let mut working = task();
            working.column = crate::board::Column::Working;
            assert!(!policy.permits_agent("commit", &working));
        }
    }

    #[test]
    fn invalid_configuration_is_rejected_before_saving() {
        for template in [
            "{unknown}: {summary}",
            "no summary",
            "{summary}\nGenerated with Claude",
        ] {
            assert!(Policy {
                commit_template: template.into(),
                ..Default::default()
            }
            .validate()
            .is_err());
        }
        assert!(Policy {
            trigger: "shell script".into(),
            ..Default::default()
        }
        .validate()
        .is_err());
        assert!(Policy {
            default_type: "fix; rm".into(),
            ..Default::default()
        }
        .validate()
        .is_err());
    }
}
